### ISSUE TITLE
Create and distribute user research survey

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-testing#1]
- [x] Approach UXR team to determine process for user research project development
 - [x] Draft research plan
 - [x] Draft survey
 - [ ] SDK team review of research plan and survey
 - [ ] Create survey in Qualtrics
 - [ ] Distribute survey (steps subject to research plan review)
   - [ ] Create GitHub issues on terraform-plugin-sdk, terraform-plugin-framework, and terraform-plugin-go repositories
   - [ ] Create Discuss post
   - [ ] Create message in #contributors-terraform Slack channel

[Research plan](https://docs.google.com/document/d/1kmh9lAToApsrlgcDNgCclnHr_H61EK0eRrCsYYtFyM0/edit)

Relevant background documents:
[HashiCorp UXR Playbook](https://docs.google.com/document/d/1xJma0TLXqhQJ44jgiYxh6sOix7ihi-ZKak4t01QETLo/edit#heading=h.b3jmdrrt17sf)
[UXR Writing Surveys Quick Guide](https://docs.google.com/document/d/1e6Q8XdLqQgUvWMhqEgPVs_DgziurOg0CaErSdOQWm8M/edit)

**Comment by bflad** [comment]
These efforts are now being driven by the Product organization, rather than the now-defunct UXR organization. We've done at least one partner survey and one internal survey since this was introduced though and gotten some minor insights. Closing for now since the Product folks will own effort tracking (I'm guessing internally) of future surveys.
