### ISSUE TITLE
Design doc: Integrating with provider servers

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-testing#10]
As well as terraform-plugin-framework providers (`tfsdk.Provider`), can the new test framework be used with providers built on:
 - SDKv2 (`schema.Provider)?
 - terraform-plugin-go (`tfprotov6.ProviderServer` including muxed providers)
 - `tfprotov5.ProviderServer`

And how does this integration point function?

The major tradeoff here is likely to be between a rich integration between the framework and test framework (restricting its use to providers built using the framework), and an interface-based approach in which the test framework would not have built-in access to certain provider data.

## Prior art

Paddy's prototype for an interface solution including discussion of other options: https://github.com/hashicorp/terraform-sdk-experiments/tree/main/paddy-testing-interfaces-1

**Comment by bflad** [comment]
This is certainly an interesting area, however I think the framework's available extensibility has already covered this for the next generation of providers. Provider developers are already able to introduce a "wrapper"/"testing" `provider.Provider` type around their "production" `provider.Provider` type. That "testing" type can handle any code wiring necessary with testing code, such as saving configured provider clients into a variable in the testing package scope. Essentially #11 really touches on what folks really want in this space. Since the framework already makes unit testing much easier for developers for a lot of their code, it is less important that there be additional provider server testing abstractions for this integration-level testing.

Aside: I will say, it would be nice if provider developers only had one way for declaring their providers under test regardless of protocol version. A future major version will most certainly drop `Providers` and `ProviderFactories` handling that relies on the prior SDK `schema.Provider` type, but it is unclear whether its worth the developer burden to also break `ProtoV5ProviderFactories` and `ProtoV6ProviderFactories` by introducing one-interface-to-rule-them-all at the same time. That would certainly be discussed in a targeted issue.
