### ISSUE TITLE
Option to refer to other resources inside resource validation

### ISSUE THREAD

**Issue by kiranms-newpage** [hashicorp/terraform-plugin-testing#160]
### terraform-plugin-testing version

```
github.com/hashicorp/terraform-plugin-testing v1.4.0
```

### Use cases

There should be some way to refer to other resources when validating (in ModifyPlan also) a particular resource. For example I am validating a resource, resource1. The validation depends upon another resource - like whether another resource with the referred id exists OR if some attribute in other resource has a specific value etc...

Let us say I am validating the below resource
```terraform
resource provider_resource_1 res1{
  field1 = ["val1"]
}
```
I need to check if "val1" is present in another resource or not
```terraform
resource provider_resource_2 res2{
  supported_values = ["val1", "val2"]
}
```
Currently when I am validating "provider_resource_1", I cant refer to any other resource.

**Comment by bflad** [comment]
Hi @kiranms-newpage 👋 Thank you for raising this.

Please note that this issue was created in the terraform-plugin-testing repository, which is a project that offers end-to-end provider testing as a wrapper for Terraform CLI commands. It seems like you may have wanted to raise this in [terraform-plugin-framework](https://github.com/hashicorp/terraform-plugin-framework), where provider resources and validation code concepts are defined. I'll try to answer this the same as if the issue was over there though.

The current design of the [Terraform Plugin Protocol](https://github.com/hashicorp/terraform/tree/main/docs/plugin-protocol), which is the interface between Terraform core and providers, is that resource operations only receive data associated to their resource instance.

In your example configuration:

```terraform
resource provider_resource_2 res2 {
  supported_values = ["val1", "val2"]
}
```

The `ValidateResourceConfig` protocol operation is sent with roughly the following request data to the provider (its not actually JSON that looks like this, but for illustrative purposes):

```json
{
  "type_name": "provider_resource_2",
  "config": {
    "supported_values": ["val1", "val2"]
  }
}
```

The same protocol design applies to `PlanResourceChange`, which is what is surfaced by the framework `ModifyPlan` functionality.

Therefore, it is not possible for the framework or any provider side code to potentially reference any other resource's configuration to create validation rules. Any sort of change to the protocol would need to be discussed as a feature request in the Terraform core issue tracker: https://github.com/hashicorp/terraform/issues

An option in the provider code would be if the API offers a way to retrieve valid/expected values, the `ModifyPlan` method of a resource could make that API call and potentially return a validation error. If you have questions about this sort of setup, please reach out in the [Terraform Plugin Development section of HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43).

Otherwise, typically this type of validation logic is expected within a configuration containing the multiple resources. For example, a [custom conditions](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions), such as `precondition` or `check` blocks may be suitable in this case. If you have questions about that configuration language functionality, there is the general [Terraform section of HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27).

Since it does not appear that there is anything actionable for this repository with this request, I'm going to close this issue. I hope the above helps though.
